### ISSUE TITLE
Capture Basler images simultaneously?

### ISSUE THREAD

**Issue by jasony2701** [jhacsonmeza/StereoBaslerUltrasound#1]
Hi,

I'm currently working on a Stereo Vision project. I saw your Issue on Pypylon on taking image array of two cameras simultaneously. Would you mind tell me whether you have successfully done it? If so, would you mind tell me the method?

Thank you for your time.

**Comment by jhacsonmeza** [comment]
Hi @jasony2701

I'm really sorry to reply you after a long time. I didn't get any notification of your issue opened here. I would like to know if you still have the same problem. Are you working with Python or C++? Because here you can see an example of acquisition of two cameras.

Sorry again.
